### ISSUE TITLE
TODO: add IPR bot to repos

### ISSUE THREAD

**Issue by lucacasonato** [wintercg/admin#13]
Blocked on #12 

Should be added to the following repos:

- [x] https://github.com/wintercg/proposal-common-minimum-api
- [x] https://github.com/wintercg/proposal-webcrypto-streams
- [x] https://github.com/wintercg/www
- [x] https://github.com/wintercg/admin

**Comment by lucacasonato** [comment]
All repos now have the IPR bot set up, and require it's check to complete before committing to "main".
