### ISSUE TITLE
TODO: register domain to host website and proposals

### ISSUE THREAD

**Issue by lucacasonato** [wintercg/admin#14]
https://wintercg.org for home page, and something like https://webcrypto-streams.proposal.wintercg.org for proposals.

We need to register this domain.

- [ ] Who should hold the domain? How does WICG do it?
- [ ] Where do we register it? (Cloudflare Registrar? :D)
- [ ] Where do we manage DNS?
- [ ] Who has access?
